spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb_test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer